"""Migrate NetworkX graph.pkl to PostgreSQL.

Note: Uses pickle to load existing graph.pkl — this is a trusted local file
generated by the Mnemo build pipeline, not untrusted external data.

Usage:
    python scripts/migrate_to_pg.py [--cache-dir .mnemo]
"""
import json
import os
import pickle  # trusted local cache file only
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache-dir", default=".mnemo")
    args = parser.parse_args()

    cache_dir = Path(args.cache_dir)
    graph_path = cache_dir / "graph.pkl"

    if not graph_path.exists():
        print(f"ERROR: {graph_path} not found")
        sys.exit(1)

    print(f"Loading graph from {graph_path}...")
    # graph.pkl is generated by our own build pipeline — trusted source
    with open(graph_path, "rb") as f:
        G = pickle.load(f)  # noqa: S301 — trusted local cache

    print(f"Graph: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")

    # Prepare import data
    nodes = []
    for name, attrs in G.nodes(data=True):
        nodes.append({
            "name": str(name),
            "entity_type": attrs.get("entity_type", attrs.get("type", "note")),
            "content": attrs.get("content", attrs.get("snippet", "")),
            "metadata": {k: v for k, v in attrs.items()
                        if k not in ("entity_type", "type", "content", "snippet")
                        and isinstance(v, (str, int, float, bool, list, dict, type(None)))},
            "source": attrs.get("source", "vault"),
            "source_path": attrs.get("path", attrs.get("source_path", "")),
        })

    edges = []
    for src, tgt, attrs in G.edges(data=True):
        edges.append({
            "source": str(src),
            "target": str(tgt),
            "relation": attrs.get("relation", attrs.get("type", "related")),
            "weight": float(attrs.get("weight", 1.0)),
        })

    print(f"Prepared {len(nodes)} nodes, {len(edges)} edges")

    # Import to PostgreSQL
    from mnemo.db import bulk_import_graph, get_stats

    result = bulk_import_graph({"nodes": nodes, "edges": edges})
    print(f"Imported: {result['nodes_imported']} nodes, {result['edges_imported']} edges")

    # Import embeddings if available
    emb_dir = cache_dir / "embeddings"
    if emb_dir.exists():
        import numpy as np
        from mnemo.db import upsert_embedding

        emb_files = list(emb_dir.glob("*.npy"))
        print(f"Found {len(emb_files)} embedding files")

        imported = 0
        for ef in emb_files:
            node_name = ef.stem
            try:
                vec = np.load(ef).tolist()
                if len(vec) == 1024:
                    upsert_embedding(node_name, vec)
                    imported += 1
            except Exception:
                pass  # skip invalid embeddings

        print(f"Imported {imported} embeddings")

    stats = get_stats()
    print(f"\nFinal stats: {json.dumps(stats, indent=2)}")


if __name__ == "__main__":
    main()
