"""Sync local .mnemo/ cache to Railway PostgreSQL via Mnemo API.

Reads the local graph.pkl (trusted, self-generated cache) and embeddings,
then pushes to the server via HTTP API.

Note: pickle is used here to load graph.pkl which is generated by our own
daily_enrich.py pipeline — not untrusted external data.

Usage:
    python scripts/sync_to_server.py [--api-url URL] [--cache-dir .mnemo]

Environment:
    MNEMO_API_URL  — Mnemo API base URL
"""
from __future__ import annotations

import argparse
import json
import os
import pickle  # noqa: S403 — loading our own trusted cache file only
import sys
import time
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError

DEFAULT_API_URL = "https://mnemo-api-production-5e7a.up.railway.app"


def api_call(base_url: str, path: str, method: str = "GET", data: dict | None = None) -> dict:
    url = f"{base_url}{path}"
    if data:
        body = json.dumps(data).encode("utf-8")
        req = Request(url, data=body, headers={"Content-Type": "application/json"}, method=method)
    else:
        req = Request(url, method=method)
    try:
        resp = urlopen(req, timeout=30)
        return json.loads(resp.read().decode())
    except HTTPError as e:
        err_body = e.read().decode() if hasattr(e, 'read') else ""
        print(f"  API error {e.code}: {err_body[:200]}")
        return {}
    except Exception as e:
        print(f"  API error: {e}")
        return {}


def load_local_graph(cache_dir: str) -> tuple:
    graph_path = Path(cache_dir) / "graph.pkl"
    if not graph_path.exists():
        print(f"ERROR: {graph_path} not found")
        sys.exit(1)

    # graph.pkl is generated by our own daily_enrich.py — trusted source
    with open(graph_path, "rb") as f:
        G = pickle.load(f)  # noqa: S301

    nodes = []
    for name, attrs in G.nodes(data=True):
        nodes.append({
            "name": str(name),
            "entity_type": attrs.get("entity_type", attrs.get("type", "note")),
            "content": attrs.get("content", attrs.get("snippet", "")),
            "source": attrs.get("source", "vault"),
            "source_path": attrs.get("path", attrs.get("source_path", "")),
        })

    edges = []
    for src, tgt, attrs in G.edges(data=True):
        edges.append({
            "source": str(src),
            "target": str(tgt),
            "relation": attrs.get("relation", attrs.get("type", "related")),
            "weight": float(attrs.get("weight", 1.0)),
        })

    return nodes, edges, G.number_of_nodes(), G.number_of_edges()


def sync_batched(api_url: str, nodes: list, edges: list, batch_size: int = 500) -> dict:
    total_n, total_e = 0, 0

    for i in range(0, len(nodes), batch_size):
        batch = nodes[i:i + batch_size]
        result = api_call(api_url, "/db/import", "POST", {"nodes": batch, "edges": []})
        total_n += result.get("nodes_imported", 0)
        print(f"  Nodes {i+1}-{i+len(batch)}: {result.get('nodes_imported',0)} imported")
        time.sleep(0.3)

    for i in range(0, len(edges), batch_size):
        batch = edges[i:i + batch_size]
        result = api_call(api_url, "/db/import", "POST", {"nodes": [], "edges": batch})
        total_e += result.get("edges_imported", 0)
        print(f"  Edges {i+1}-{i+len(batch)}: {result.get('edges_imported',0)} imported")
        time.sleep(0.3)

    return {"nodes_imported": total_n, "edges_imported": total_e}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--api-url", default=os.getenv("MNEMO_API_URL", DEFAULT_API_URL))
    parser.add_argument("--cache-dir", default=".mnemo")
    args = parser.parse_args()

    print(f"Mnemo Sync -> {args.api_url}")

    # Check server
    health = api_call(args.api_url, "/v2/health")
    db = health.get("database", {})
    if not db.get("available"):
        print("ERROR: Database not available")
        sys.exit(1)
    print(f"Server DB: {db.get('node_count',0)} nodes, {db.get('edge_count',0)} edges")

    # Load local
    nodes, edges, n, e = load_local_graph(args.cache_dir)
    print(f"Local: {n} nodes, {e} edges")

    # Sync
    print("Syncing...")
    result = sync_batched(args.api_url, nodes, edges)
    print(f"Done: {result['nodes_imported']} nodes, {result['edges_imported']} edges")

    # Final stats
    stats = api_call(args.api_url, "/db/stats")
    print(f"Server now: {stats.get('node_count','?')} nodes, {stats.get('edge_count','?')} edges")


if __name__ == "__main__":
    main()
